# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jhyunlee/3FS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jhyunlee/3FS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\" \"devel\" \"runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jhyunlee/3FS/CMakeFiles /home/jhyunlee/3FS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jhyunlee/3FS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/jhyunlee/3FS/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named check-format

# Build rule for target.
check-format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-format
.PHONY : check-format

# fast build rule for target.
check-format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-format.dir/build.make CMakeFiles/check-format.dir/build
.PHONY : check-format/fast

#=============================================================================
# Target rules for targets named clang-tidy

# Build rule for target.
clang-tidy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clang-tidy
.PHONY : clang-tidy

# fast build rule for target.
clang-tidy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clang-tidy.dir/build.make CMakeFiles/clang-tidy.dir/build
.PHONY : clang-tidy/fast

#=============================================================================
# Target rules for targets named clang-tidy-fix

# Build rule for target.
clang-tidy-fix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clang-tidy-fix
.PHONY : clang-tidy-fix

# fast build rule for target.
clang-tidy-fix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clang-tidy-fix.dir/build.make CMakeFiles/clang-tidy-fix.dir/build
.PHONY : clang-tidy-fix/fast

#=============================================================================
# Target rules for targets named dump-config

# Build rule for target.
dump-config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dump-config
.PHONY : dump-config

# fast build rule for target.
dump-config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dump-config.dir/build.make CMakeFiles/dump-config.dir/build
.PHONY : dump-config/fast

#=============================================================================
# Target rules for targets named Hf3fsJemalloc_project

# Build rule for target.
Hf3fsJemalloc_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hf3fsJemalloc_project
.PHONY : Hf3fsJemalloc_project

# fast build rule for target.
Hf3fsJemalloc_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Hf3fsJemalloc_project.dir/build.make CMakeFiles/Hf3fsJemalloc_project.dir/build
.PHONY : Hf3fsJemalloc_project/fast

#=============================================================================
# Target rules for targets named apache-arrow-cpp

# Build rule for target.
apache-arrow-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apache-arrow-cpp
.PHONY : apache-arrow-cpp

# fast build rule for target.
apache-arrow-cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apache-arrow-cpp.dir/build.make CMakeFiles/apache-arrow-cpp.dir/build
.PHONY : apache-arrow-cpp/fast

#=============================================================================
# Target rules for targets named cargo_build_all

# Build rule for target.
cargo_build_all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cargo_build_all
.PHONY : cargo_build_all

# fast build rule for target.
cargo_build_all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cargo_build_all.dir/build.make CMakeFiles/cargo_build_all.dir/build
.PHONY : cargo_build_all/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f third_party/fmt/CMakeFiles/fmt.dir/build.make third_party/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/CMakeFiles/clean-all.dir/build.make third_party/zstd/build/cmake/CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named libzstd_shared

# Build rule for target.
libzstd_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libzstd_shared
.PHONY : libzstd_shared

# fast build rule for target.
libzstd_shared/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/lib/CMakeFiles/libzstd_shared.dir/build.make third_party/zstd/build/cmake/lib/CMakeFiles/libzstd_shared.dir/build
.PHONY : libzstd_shared/fast

#=============================================================================
# Target rules for targets named libzstd_static

# Build rule for target.
libzstd_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libzstd_static
.PHONY : libzstd_static

# fast build rule for target.
libzstd_static/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/lib/CMakeFiles/libzstd_static.dir/build.make third_party/zstd/build/cmake/lib/CMakeFiles/libzstd_static.dir/build
.PHONY : libzstd_static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/lib/CMakeFiles/uninstall.dir/build.make third_party/zstd/build/cmake/lib/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named zstd

# Build rule for target.
zstd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd
.PHONY : zstd

# fast build rule for target.
zstd/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/zstd.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/zstd.dir/build
.PHONY : zstd/fast

#=============================================================================
# Target rules for targets named zstdcat

# Build rule for target.
zstdcat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdcat
.PHONY : zstdcat

# fast build rule for target.
zstdcat/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/zstdcat.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/zstdcat.dir/build
.PHONY : zstdcat/fast

#=============================================================================
# Target rules for targets named unzstd

# Build rule for target.
unzstd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unzstd
.PHONY : unzstd

# fast build rule for target.
unzstd/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/unzstd.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/unzstd.dir/build
.PHONY : unzstd/fast

#=============================================================================
# Target rules for targets named zstd.1

# Build rule for target.
zstd.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd.1
.PHONY : zstd.1

# fast build rule for target.
zstd.1/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/zstd.1.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/zstd.1.dir/build
.PHONY : zstd.1/fast

#=============================================================================
# Target rules for targets named zstdgrep.1

# Build rule for target.
zstdgrep.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdgrep.1
.PHONY : zstdgrep.1

# fast build rule for target.
zstdgrep.1/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/zstdgrep.1.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/zstdgrep.1.dir/build
.PHONY : zstdgrep.1/fast

#=============================================================================
# Target rules for targets named zstdless.1

# Build rule for target.
zstdless.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdless.1
.PHONY : zstdless.1

# fast build rule for target.
zstdless.1/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/zstdless.1.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/zstdless.1.dir/build
.PHONY : zstdless.1/fast

#=============================================================================
# Target rules for targets named zstdcat.1

# Build rule for target.
zstdcat.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdcat.1
.PHONY : zstdcat.1

# fast build rule for target.
zstdcat.1/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/zstdcat.1.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/zstdcat.1.dir/build
.PHONY : zstdcat.1/fast

#=============================================================================
# Target rules for targets named unzstd.1

# Build rule for target.
unzstd.1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unzstd.1
.PHONY : unzstd.1

# fast build rule for target.
unzstd.1/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/unzstd.1.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/unzstd.1.dir/build
.PHONY : unzstd.1/fast

#=============================================================================
# Target rules for targets named zstd-frugal

# Build rule for target.
zstd-frugal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstd-frugal
.PHONY : zstd-frugal

# fast build rule for target.
zstd-frugal/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/zstd-frugal.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/zstd-frugal.dir/build
.PHONY : zstd-frugal/fast

#=============================================================================
# Target rules for targets named zstdmt

# Build rule for target.
zstdmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zstdmt
.PHONY : zstdmt

# fast build rule for target.
zstdmt/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zstd/build/cmake/programs/CMakeFiles/zstdmt.dir/build.make third_party/zstd/build/cmake/programs/CMakeFiles/zstdmt.dir/build
.PHONY : zstdmt/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f third_party/googletest/googlemock/CMakeFiles/gmock.dir/build.make third_party/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f third_party/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make third_party/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f third_party/googletest/googletest/CMakeFiles/gtest.dir/build.make third_party/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f third_party/googletest/googletest/CMakeFiles/gtest_main.dir/build.make third_party/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named folly_base

# Build rule for target.
folly_base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 folly_base
.PHONY : folly_base

# fast build rule for target.
folly_base/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/CMakeFiles/folly_base.dir/build.make third_party/folly/CMakeFiles/folly_base.dir/build
.PHONY : folly_base/fast

#=============================================================================
# Target rules for targets named folly

# Build rule for target.
folly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 folly
.PHONY : folly

# fast build rule for target.
folly/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/CMakeFiles/folly.dir/build.make third_party/folly/CMakeFiles/folly.dir/build
.PHONY : folly/fast

#=============================================================================
# Target rules for targets named folly_test_util

# Build rule for target.
folly_test_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 folly_test_util
.PHONY : folly_test_util

# fast build rule for target.
folly_test_util/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/CMakeFiles/folly_test_util.dir/build.make third_party/folly/CMakeFiles/folly_test_util.dir/build
.PHONY : folly_test_util/fast

#=============================================================================
# Target rules for targets named follybenchmark

# Build rule for target.
follybenchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 follybenchmark
.PHONY : follybenchmark

# fast build rule for target.
follybenchmark/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/folly/CMakeFiles/follybenchmark.dir/build.make third_party/folly/folly/CMakeFiles/follybenchmark.dir/build
.PHONY : follybenchmark/fast

#=============================================================================
# Target rules for targets named folly_exception_tracer_base

# Build rule for target.
folly_exception_tracer_base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 folly_exception_tracer_base
.PHONY : folly_exception_tracer_base

# fast build rule for target.
folly_exception_tracer_base/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/folly/experimental/exception_tracer/CMakeFiles/folly_exception_tracer_base.dir/build.make third_party/folly/folly/experimental/exception_tracer/CMakeFiles/folly_exception_tracer_base.dir/build
.PHONY : folly_exception_tracer_base/fast

#=============================================================================
# Target rules for targets named folly_exception_tracer

# Build rule for target.
folly_exception_tracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 folly_exception_tracer
.PHONY : folly_exception_tracer

# fast build rule for target.
folly_exception_tracer/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/folly/experimental/exception_tracer/CMakeFiles/folly_exception_tracer.dir/build.make third_party/folly/folly/experimental/exception_tracer/CMakeFiles/folly_exception_tracer.dir/build
.PHONY : folly_exception_tracer/fast

#=============================================================================
# Target rules for targets named folly_exception_counter

# Build rule for target.
folly_exception_counter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 folly_exception_counter
.PHONY : folly_exception_counter

# fast build rule for target.
folly_exception_counter/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/folly/experimental/exception_tracer/CMakeFiles/folly_exception_counter.dir/build.make third_party/folly/folly/experimental/exception_tracer/CMakeFiles/folly_exception_counter.dir/build
.PHONY : folly_exception_counter/fast

#=============================================================================
# Target rules for targets named logging_example

# Build rule for target.
logging_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logging_example
.PHONY : logging_example

# fast build rule for target.
logging_example/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/folly/logging/example/CMakeFiles/logging_example.dir/build.make third_party/folly/folly/logging/example/CMakeFiles/logging_example.dir/build
.PHONY : logging_example/fast

#=============================================================================
# Target rules for targets named logging_example_lib

# Build rule for target.
logging_example_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logging_example_lib
.PHONY : logging_example_lib

# fast build rule for target.
logging_example_lib/fast:
	$(MAKE) $(MAKESILENT) -f third_party/folly/folly/logging/example/CMakeFiles/logging_example_lib.dir/build.make third_party/folly/folly/logging/example/CMakeFiles/logging_example_lib.dir/build
.PHONY : logging_example_lib/fast

#=============================================================================
# Target rules for targets named leveldb

# Build rule for target.
leveldb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leveldb
.PHONY : leveldb

# fast build rule for target.
leveldb/fast:
	$(MAKE) $(MAKESILENT) -f third_party/leveldb/CMakeFiles/leveldb.dir/build.make third_party/leveldb/CMakeFiles/leveldb.dir/build
.PHONY : leveldb/fast

#=============================================================================
# Target rules for targets named leveldbutil

# Build rule for target.
leveldbutil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leveldbutil
.PHONY : leveldbutil

# fast build rule for target.
leveldbutil/fast:
	$(MAKE) $(MAKESILENT) -f third_party/leveldb/CMakeFiles/leveldbutil.dir/build.make third_party/leveldb/CMakeFiles/leveldbutil.dir/build
.PHONY : leveldbutil/fast

#=============================================================================
# Target rules for targets named rocksdb

# Build rule for target.
rocksdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rocksdb
.PHONY : rocksdb

# fast build rule for target.
rocksdb/fast:
	$(MAKE) $(MAKESILENT) -f third_party/rocksdb/CMakeFiles/rocksdb.dir/build.make third_party/rocksdb/CMakeFiles/rocksdb.dir/build
.PHONY : rocksdb/fast

#=============================================================================
# Target rules for targets named rocksdb-shared

# Build rule for target.
rocksdb-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rocksdb-shared
.PHONY : rocksdb-shared

# fast build rule for target.
rocksdb-shared/fast:
	$(MAKE) $(MAKESILENT) -f third_party/rocksdb/CMakeFiles/rocksdb-shared.dir/build.make third_party/rocksdb/CMakeFiles/rocksdb-shared.dir/build
.PHONY : rocksdb-shared/fast

#=============================================================================
# Target rules for targets named block_cache_trace_analyzer_tool

# Build rule for target.
block_cache_trace_analyzer_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 block_cache_trace_analyzer_tool
.PHONY : block_cache_trace_analyzer_tool

# fast build rule for target.
block_cache_trace_analyzer_tool/fast:
	$(MAKE) $(MAKESILENT) -f third_party/rocksdb/CMakeFiles/block_cache_trace_analyzer_tool.dir/build.make third_party/rocksdb/CMakeFiles/block_cache_trace_analyzer_tool.dir/build
.PHONY : block_cache_trace_analyzer_tool/fast

#=============================================================================
# Target rules for targets named trace_analyzer

# Build rule for target.
trace_analyzer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trace_analyzer
.PHONY : trace_analyzer

# fast build rule for target.
trace_analyzer/fast:
	$(MAKE) $(MAKESILENT) -f third_party/rocksdb/CMakeFiles/trace_analyzer.dir/build.make third_party/rocksdb/CMakeFiles/trace_analyzer.dir/build
.PHONY : trace_analyzer/fast

#=============================================================================
# Target rules for targets named core_tools

# Build rule for target.
core_tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_tools
.PHONY : core_tools

# fast build rule for target.
core_tools/fast:
	$(MAKE) $(MAKESILENT) -f third_party/rocksdb/CMakeFiles/core_tools.dir/build.make third_party/rocksdb/CMakeFiles/core_tools.dir/build
.PHONY : core_tools/fast

#=============================================================================
# Target rules for targets named sst_dump

# Build rule for target.
sst_dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sst_dump
.PHONY : sst_dump

# fast build rule for target.
sst_dump/fast:
	$(MAKE) $(MAKESILENT) -f third_party/rocksdb/tools/CMakeFiles/sst_dump.dir/build.make third_party/rocksdb/tools/CMakeFiles/sst_dump.dir/build
.PHONY : sst_dump/fast

#=============================================================================
# Target rules for targets named ldb

# Build rule for target.
ldb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ldb
.PHONY : ldb

# fast build rule for target.
ldb/fast:
	$(MAKE) $(MAKESILENT) -f third_party/rocksdb/tools/CMakeFiles/ldb.dir/build.make third_party/rocksdb/tools/CMakeFiles/ldb.dir/build
.PHONY : ldb/fast

#=============================================================================
# Target rules for targets named scn

# Build rule for target.
scn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scn
.PHONY : scn

# fast build rule for target.
scn/fast:
	$(MAKE) $(MAKESILENT) -f third_party/scnlib/CMakeFiles/scn.dir/build.make third_party/scnlib/CMakeFiles/scn.dir/build
.PHONY : scn/fast

#=============================================================================
# Target rules for targets named mimalloc

# Build rule for target.
mimalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc
.PHONY : mimalloc

# fast build rule for target.
mimalloc/fast:
	$(MAKE) $(MAKESILENT) -f third_party/mimalloc/CMakeFiles/mimalloc.dir/build.make third_party/mimalloc/CMakeFiles/mimalloc.dir/build
.PHONY : mimalloc/fast

#=============================================================================
# Target rules for targets named mimalloc-static

# Build rule for target.
mimalloc-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-static
.PHONY : mimalloc-static

# fast build rule for target.
mimalloc-static/fast:
	$(MAKE) $(MAKESILENT) -f third_party/mimalloc/CMakeFiles/mimalloc-static.dir/build.make third_party/mimalloc/CMakeFiles/mimalloc-static.dir/build
.PHONY : mimalloc-static/fast

#=============================================================================
# Target rules for targets named mimalloc-obj

# Build rule for target.
mimalloc-obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-obj
.PHONY : mimalloc-obj

# fast build rule for target.
mimalloc-obj/fast:
	$(MAKE) $(MAKESILENT) -f third_party/mimalloc/CMakeFiles/mimalloc-obj.dir/build.make third_party/mimalloc/CMakeFiles/mimalloc-obj.dir/build
.PHONY : mimalloc-obj/fast

#=============================================================================
# Target rules for targets named mimalloc-obj-target

# Build rule for target.
mimalloc-obj-target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-obj-target
.PHONY : mimalloc-obj-target

# fast build rule for target.
mimalloc-obj-target/fast:
	$(MAKE) $(MAKESILENT) -f third_party/mimalloc/CMakeFiles/mimalloc-obj-target.dir/build.make third_party/mimalloc/CMakeFiles/mimalloc-obj-target.dir/build
.PHONY : mimalloc-obj-target/fast

#=============================================================================
# Target rules for targets named mimalloc-test-api

# Build rule for target.
mimalloc-test-api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-test-api
.PHONY : mimalloc-test-api

# fast build rule for target.
mimalloc-test-api/fast:
	$(MAKE) $(MAKESILENT) -f third_party/mimalloc/CMakeFiles/mimalloc-test-api.dir/build.make third_party/mimalloc/CMakeFiles/mimalloc-test-api.dir/build
.PHONY : mimalloc-test-api/fast

#=============================================================================
# Target rules for targets named mimalloc-test-api-fill

# Build rule for target.
mimalloc-test-api-fill: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-test-api-fill
.PHONY : mimalloc-test-api-fill

# fast build rule for target.
mimalloc-test-api-fill/fast:
	$(MAKE) $(MAKESILENT) -f third_party/mimalloc/CMakeFiles/mimalloc-test-api-fill.dir/build.make third_party/mimalloc/CMakeFiles/mimalloc-test-api-fill.dir/build
.PHONY : mimalloc-test-api-fill/fast

#=============================================================================
# Target rules for targets named mimalloc-test-stress

# Build rule for target.
mimalloc-test-stress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-test-stress
.PHONY : mimalloc-test-stress

# fast build rule for target.
mimalloc-test-stress/fast:
	$(MAKE) $(MAKESILENT) -f third_party/mimalloc/CMakeFiles/mimalloc-test-stress.dir/build.make third_party/mimalloc/CMakeFiles/mimalloc-test-stress.dir/build
.PHONY : mimalloc-test-stress/fast

#=============================================================================
# Target rules for targets named clickhouse-cpp-lib

# Build rule for target.
clickhouse-cpp-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clickhouse-cpp-lib
.PHONY : clickhouse-cpp-lib

# fast build rule for target.
clickhouse-cpp-lib/fast:
	$(MAKE) $(MAKESILENT) -f third_party/clickhouse-cpp/clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/build.make third_party/clickhouse-cpp/clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/build
.PHONY : clickhouse-cpp-lib/fast

#=============================================================================
# Target rules for targets named clickhouse-cpp-lib-static

# Build rule for target.
clickhouse-cpp-lib-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clickhouse-cpp-lib-static
.PHONY : clickhouse-cpp-lib-static

# fast build rule for target.
clickhouse-cpp-lib-static/fast:
	$(MAKE) $(MAKESILENT) -f third_party/clickhouse-cpp/clickhouse/CMakeFiles/clickhouse-cpp-lib-static.dir/build.make third_party/clickhouse-cpp/clickhouse/CMakeFiles/clickhouse-cpp-lib-static.dir/build
.PHONY : clickhouse-cpp-lib-static/fast

#=============================================================================
# Target rules for targets named absl-lib

# Build rule for target.
absl-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 absl-lib
.PHONY : absl-lib

# fast build rule for target.
absl-lib/fast:
	$(MAKE) $(MAKESILENT) -f third_party/clickhouse-cpp/contrib/absl/CMakeFiles/absl-lib.dir/build.make third_party/clickhouse-cpp/contrib/absl/CMakeFiles/absl-lib.dir/build
.PHONY : absl-lib/fast

#=============================================================================
# Target rules for targets named cityhash-lib

# Build rule for target.
cityhash-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cityhash-lib
.PHONY : cityhash-lib

# fast build rule for target.
cityhash-lib/fast:
	$(MAKE) $(MAKESILENT) -f third_party/clickhouse-cpp/contrib/cityhash/CMakeFiles/cityhash-lib.dir/build.make third_party/clickhouse-cpp/contrib/cityhash/CMakeFiles/cityhash-lib.dir/build
.PHONY : cityhash-lib/fast

#=============================================================================
# Target rules for targets named lz4-lib

# Build rule for target.
lz4-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lz4-lib
.PHONY : lz4-lib

# fast build rule for target.
lz4-lib/fast:
	$(MAKE) $(MAKESILENT) -f third_party/clickhouse-cpp/contrib/lz4/CMakeFiles/lz4-lib.dir/build.make third_party/clickhouse-cpp/contrib/lz4/CMakeFiles/lz4-lib.dir/build
.PHONY : lz4-lib/fast

#=============================================================================
# Target rules for targets named 3fs_liburing

# Build rule for target.
3fs_liburing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3fs_liburing
.PHONY : 3fs_liburing

# fast build rule for target.
3fs_liburing/fast:
	$(MAKE) $(MAKESILENT) -f third_party/liburing-cmake/CMakeFiles/3fs_liburing.dir/build.make third_party/liburing-cmake/CMakeFiles/3fs_liburing.dir/build
.PHONY : 3fs_liburing/fast

#=============================================================================
# Target rules for targets named core-user-fbs

# Build rule for target.
core-user-fbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core-user-fbs
.PHONY : core-user-fbs

# fast build rule for target.
core-user-fbs/fast:
	$(MAKE) $(MAKESILENT) -f src/fbs/core/user/CMakeFiles/core-user-fbs.dir/build.make src/fbs/core/user/CMakeFiles/core-user-fbs.dir/build
.PHONY : core-user-fbs/fast

#=============================================================================
# Target rules for targets named core-service-fbs

# Build rule for target.
core-service-fbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core-service-fbs
.PHONY : core-service-fbs

# fast build rule for target.
core-service-fbs/fast:
	$(MAKE) $(MAKESILENT) -f src/fbs/core/service/CMakeFiles/core-service-fbs.dir/build.make src/fbs/core/service/CMakeFiles/core-service-fbs.dir/build
.PHONY : core-service-fbs/fast

#=============================================================================
# Target rules for targets named mgmtd-fbs

# Build rule for target.
mgmtd-fbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mgmtd-fbs
.PHONY : mgmtd-fbs

# fast build rule for target.
mgmtd-fbs/fast:
	$(MAKE) $(MAKESILENT) -f src/fbs/mgmtd/CMakeFiles/mgmtd-fbs.dir/build.make src/fbs/mgmtd/CMakeFiles/mgmtd-fbs.dir/build
.PHONY : mgmtd-fbs/fast

#=============================================================================
# Target rules for targets named meta-fbs

# Build rule for target.
meta-fbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meta-fbs
.PHONY : meta-fbs

# fast build rule for target.
meta-fbs/fast:
	$(MAKE) $(MAKESILENT) -f src/fbs/meta/CMakeFiles/meta-fbs.dir/build.make src/fbs/meta/CMakeFiles/meta-fbs.dir/build
.PHONY : meta-fbs/fast

#=============================================================================
# Target rules for targets named storage-fbs

# Build rule for target.
storage-fbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage-fbs
.PHONY : storage-fbs

# fast build rule for target.
storage-fbs/fast:
	$(MAKE) $(MAKESILENT) -f src/fbs/storage/CMakeFiles/storage-fbs.dir/build.make src/fbs/storage/CMakeFiles/storage-fbs.dir/build
.PHONY : storage-fbs/fast

#=============================================================================
# Target rules for targets named MonitorCollectorService-fbs

# Build rule for target.
MonitorCollectorService-fbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MonitorCollectorService-fbs
.PHONY : MonitorCollectorService-fbs

# fast build rule for target.
MonitorCollectorService-fbs/fast:
	$(MAKE) $(MAKESILENT) -f src/fbs/monitor_collector/CMakeFiles/MonitorCollectorService-fbs.dir/build.make src/fbs/monitor_collector/CMakeFiles/MonitorCollectorService-fbs.dir/build
.PHONY : MonitorCollectorService-fbs/fast

#=============================================================================
# Target rules for targets named simple_example-fbs

# Build rule for target.
simple_example-fbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_example-fbs
.PHONY : simple_example-fbs

# fast build rule for target.
simple_example-fbs/fast:
	$(MAKE) $(MAKESILENT) -f src/fbs/simple_example/CMakeFiles/simple_example-fbs.dir/build.make src/fbs/simple_example/CMakeFiles/simple_example-fbs.dir/build
.PHONY : simple_example-fbs/fast

#=============================================================================
# Target rules for targets named migration-fbs

# Build rule for target.
migration-fbs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 migration-fbs
.PHONY : migration-fbs

# fast build rule for target.
migration-fbs/fast:
	$(MAKE) $(MAKESILENT) -f src/fbs/migration/CMakeFiles/migration-fbs.dir/build.make src/fbs/migration/CMakeFiles/migration-fbs.dir/build
.PHONY : migration-fbs/fast

#=============================================================================
# Target rules for targets named AlwaysCheckGit

# Build rule for target.
AlwaysCheckGit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AlwaysCheckGit
.PHONY : AlwaysCheckGit

# fast build rule for target.
AlwaysCheckGit/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/AlwaysCheckGit.dir/build.make src/common/CMakeFiles/AlwaysCheckGit.dir/build
.PHONY : AlwaysCheckGit/fast

#=============================================================================
# Target rules for targets named version-info

# Build rule for target.
version-info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 version-info
.PHONY : version-info

# fast build rule for target.
version-info/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/version-info.dir/build.make src/common/CMakeFiles/version-info.dir/build
.PHONY : version-info/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/common.dir/build.make src/common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named hf3fs_common_shared

# Build rule for target.
hf3fs_common_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hf3fs_common_shared
.PHONY : hf3fs_common_shared

# fast build rule for target.
hf3fs_common_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/common/CMakeFiles/hf3fs_common_shared.dir/build.make src/common/CMakeFiles/hf3fs_common_shared.dir/build
.PHONY : hf3fs_common_shared/fast

#=============================================================================
# Target rules for targets named meta

# Build rule for target.
meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meta
.PHONY : meta

# fast build rule for target.
meta/fast:
	$(MAKE) $(MAKESILENT) -f src/meta/CMakeFiles/meta.dir/build.make src/meta/CMakeFiles/meta.dir/build
.PHONY : meta/fast

#=============================================================================
# Target rules for targets named meta_main

# Build rule for target.
meta_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meta_main
.PHONY : meta_main

# fast build rule for target.
meta_main/fast:
	$(MAKE) $(MAKESILENT) -f src/meta/CMakeFiles/meta_main.dir/build.make src/meta/CMakeFiles/meta_main.dir/build
.PHONY : meta_main/fast

#=============================================================================
# Target rules for targets named common-cli

# Build rule for target.
common-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common-cli
.PHONY : common-cli

# fast build rule for target.
common-cli/fast:
	$(MAKE) $(MAKESILENT) -f src/client/cli/common/CMakeFiles/common-cli.dir/build.make src/client/cli/common/CMakeFiles/common-cli.dir/build
.PHONY : common-cli/fast

#=============================================================================
# Target rules for targets named admin-cli

# Build rule for target.
admin-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 admin-cli
.PHONY : admin-cli

# fast build rule for target.
admin-cli/fast:
	$(MAKE) $(MAKESILENT) -f src/client/cli/admin/CMakeFiles/admin-cli.dir/build.make src/client/cli/admin/CMakeFiles/admin-cli.dir/build
.PHONY : admin-cli/fast

#=============================================================================
# Target rules for targets named admin_cli

# Build rule for target.
admin_cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 admin_cli
.PHONY : admin_cli

# fast build rule for target.
admin_cli/fast:
	$(MAKE) $(MAKESILENT) -f src/client/bin/CMakeFiles/admin_cli.dir/build.make src/client/bin/CMakeFiles/admin_cli.dir/build
.PHONY : admin_cli/fast

#=============================================================================
# Target rules for targets named mgmtd-client

# Build rule for target.
mgmtd-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mgmtd-client
.PHONY : mgmtd-client

# fast build rule for target.
mgmtd-client/fast:
	$(MAKE) $(MAKESILENT) -f src/client/mgmtd/CMakeFiles/mgmtd-client.dir/build.make src/client/mgmtd/CMakeFiles/mgmtd-client.dir/build
.PHONY : mgmtd-client/fast

#=============================================================================
# Target rules for targets named meta-client

# Build rule for target.
meta-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meta-client
.PHONY : meta-client

# fast build rule for target.
meta-client/fast:
	$(MAKE) $(MAKESILENT) -f src/client/meta/CMakeFiles/meta-client.dir/build.make src/client/meta/CMakeFiles/meta-client.dir/build
.PHONY : meta-client/fast

#=============================================================================
# Target rules for targets named storage-client

# Build rule for target.
storage-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage-client
.PHONY : storage-client

# fast build rule for target.
storage-client/fast:
	$(MAKE) $(MAKESILENT) -f src/client/storage/CMakeFiles/storage-client.dir/build.make src/client/storage/CMakeFiles/storage-client.dir/build
.PHONY : storage-client/fast

#=============================================================================
# Target rules for targets named core-client

# Build rule for target.
core-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core-client
.PHONY : core-client

# fast build rule for target.
core-client/fast:
	$(MAKE) $(MAKESILENT) -f src/client/core/CMakeFiles/core-client.dir/build.make src/client/core/CMakeFiles/core-client.dir/build
.PHONY : core-client/fast

#=============================================================================
# Target rules for targets named client-lib-common

# Build rule for target.
client-lib-common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client-lib-common
.PHONY : client-lib-common

# fast build rule for target.
client-lib-common/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/common/CMakeFiles/client-lib-common.dir/build.make src/lib/common/CMakeFiles/client-lib-common.dir/build
.PHONY : client-lib-common/fast

#=============================================================================
# Target rules for targets named hf3fs_api

# Build rule for target.
hf3fs_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hf3fs_api
.PHONY : hf3fs_api

# fast build rule for target.
hf3fs_api/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/api/CMakeFiles/hf3fs_api.dir/build.make src/lib/api/CMakeFiles/hf3fs_api.dir/build
.PHONY : hf3fs_api/fast

#=============================================================================
# Target rules for targets named hf3fs_api_shared

# Build rule for target.
hf3fs_api_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hf3fs_api_shared
.PHONY : hf3fs_api_shared

# fast build rule for target.
hf3fs_api_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/api/CMakeFiles/hf3fs_api_shared.dir/build.make src/lib/api/CMakeFiles/hf3fs_api_shared.dir/build
.PHONY : hf3fs_api_shared/fast

#=============================================================================
# Target rules for targets named hf3fs_py_usrbio

# Build rule for target.
hf3fs_py_usrbio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hf3fs_py_usrbio
.PHONY : hf3fs_py_usrbio

# fast build rule for target.
hf3fs_py_usrbio/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/py/CMakeFiles/hf3fs_py_usrbio.dir/build.make src/lib/py/CMakeFiles/hf3fs_py_usrbio.dir/build
.PHONY : hf3fs_py_usrbio/fast

#=============================================================================
# Target rules for targets named memory-common

# Build rule for target.
memory-common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory-common
.PHONY : memory-common

# fast build rule for target.
memory-common/fast:
	$(MAKE) $(MAKESILENT) -f src/memory/common/CMakeFiles/memory-common.dir/build.make src/memory/common/CMakeFiles/memory-common.dir/build
.PHONY : memory-common/fast

#=============================================================================
# Target rules for targets named leveldb_logger

# Build rule for target.
leveldb_logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leveldb_logger
.PHONY : leveldb_logger

# fast build rule for target.
leveldb_logger/fast:
	$(MAKE) $(MAKESILENT) -f src/kv/CMakeFiles/leveldb_logger.dir/build.make src/kv/CMakeFiles/leveldb_logger.dir/build
.PHONY : leveldb_logger/fast

#=============================================================================
# Target rules for targets named kv

# Build rule for target.
kv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kv
.PHONY : kv

# fast build rule for target.
kv/fast:
	$(MAKE) $(MAKESILENT) -f src/kv/CMakeFiles/kv.dir/build.make src/kv/CMakeFiles/kv.dir/build
.PHONY : kv/fast

#=============================================================================
# Target rules for targets named chunk_engine

# Build rule for target.
chunk_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chunk_engine
.PHONY : chunk_engine

# fast build rule for target.
chunk_engine/fast:
	$(MAKE) $(MAKESILENT) -f src/storage/CMakeFiles/chunk_engine.dir/build.make src/storage/CMakeFiles/chunk_engine.dir/build
.PHONY : chunk_engine/fast

#=============================================================================
# Target rules for targets named storage

# Build rule for target.
storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage
.PHONY : storage

# fast build rule for target.
storage/fast:
	$(MAKE) $(MAKESILENT) -f src/storage/CMakeFiles/storage.dir/build.make src/storage/CMakeFiles/storage.dir/build
.PHONY : storage/fast

#=============================================================================
# Target rules for targets named storage_main

# Build rule for target.
storage_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage_main
.PHONY : storage_main

# fast build rule for target.
storage_main/fast:
	$(MAKE) $(MAKESILENT) -f src/storage/CMakeFiles/storage_main.dir/build.make src/storage/CMakeFiles/storage_main.dir/build
.PHONY : storage_main/fast

#=============================================================================
# Target rules for targets named mgmtd

# Build rule for target.
mgmtd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mgmtd
.PHONY : mgmtd

# fast build rule for target.
mgmtd/fast:
	$(MAKE) $(MAKESILENT) -f src/mgmtd/CMakeFiles/mgmtd.dir/build.make src/mgmtd/CMakeFiles/mgmtd.dir/build
.PHONY : mgmtd/fast

#=============================================================================
# Target rules for targets named mgmtd_main

# Build rule for target.
mgmtd_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mgmtd_main
.PHONY : mgmtd_main

# fast build rule for target.
mgmtd_main/fast:
	$(MAKE) $(MAKESILENT) -f src/mgmtd/CMakeFiles/mgmtd_main.dir/build.make src/mgmtd/CMakeFiles/mgmtd_main.dir/build
.PHONY : mgmtd_main/fast

#=============================================================================
# Target rules for targets named fdb

# Build rule for target.
fdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fdb
.PHONY : fdb

# fast build rule for target.
fdb/fast:
	$(MAKE) $(MAKESILENT) -f src/fdb/CMakeFiles/fdb.dir/build.make src/fdb/CMakeFiles/fdb.dir/build
.PHONY : fdb/fast

#=============================================================================
# Target rules for targets named stubs-common

# Build rule for target.
stubs-common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stubs-common
.PHONY : stubs-common

# fast build rule for target.
stubs-common/fast:
	$(MAKE) $(MAKESILENT) -f src/stubs/common/CMakeFiles/stubs-common.dir/build.make src/stubs/common/CMakeFiles/stubs-common.dir/build
.PHONY : stubs-common/fast

#=============================================================================
# Target rules for targets named meta-stub

# Build rule for target.
meta-stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meta-stub
.PHONY : meta-stub

# fast build rule for target.
meta-stub/fast:
	$(MAKE) $(MAKESILENT) -f src/stubs/MetaService/CMakeFiles/meta-stub.dir/build.make src/stubs/MetaService/CMakeFiles/meta-stub.dir/build
.PHONY : meta-stub/fast

#=============================================================================
# Target rules for targets named mgmtd-stub

# Build rule for target.
mgmtd-stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mgmtd-stub
.PHONY : mgmtd-stub

# fast build rule for target.
mgmtd-stub/fast:
	$(MAKE) $(MAKESILENT) -f src/stubs/mgmtd/CMakeFiles/mgmtd-stub.dir/build.make src/stubs/mgmtd/CMakeFiles/mgmtd-stub.dir/build
.PHONY : mgmtd-stub/fast

#=============================================================================
# Target rules for targets named core-stub

# Build rule for target.
core-stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core-stub
.PHONY : core-stub

# fast build rule for target.
core-stub/fast:
	$(MAKE) $(MAKESILENT) -f src/stubs/core/CMakeFiles/core-stub.dir/build.make src/stubs/core/CMakeFiles/core-stub.dir/build
.PHONY : core-stub/fast

#=============================================================================
# Target rules for targets named monitor_collector

# Build rule for target.
monitor_collector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monitor_collector
.PHONY : monitor_collector

# fast build rule for target.
monitor_collector/fast:
	$(MAKE) $(MAKESILENT) -f src/monitor_collector/CMakeFiles/monitor_collector.dir/build.make src/monitor_collector/CMakeFiles/monitor_collector.dir/build
.PHONY : monitor_collector/fast

#=============================================================================
# Target rules for targets named monitor_collector_main

# Build rule for target.
monitor_collector_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 monitor_collector_main
.PHONY : monitor_collector_main

# fast build rule for target.
monitor_collector_main/fast:
	$(MAKE) $(MAKESILENT) -f src/monitor_collector/CMakeFiles/monitor_collector_main.dir/build.make src/monitor_collector/CMakeFiles/monitor_collector_main.dir/build
.PHONY : monitor_collector_main/fast

#=============================================================================
# Target rules for targets named analytics

# Build rule for target.
analytics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 analytics
.PHONY : analytics

# fast build rule for target.
analytics/fast:
	$(MAKE) $(MAKESILENT) -f src/analytics/CMakeFiles/analytics.dir/build.make src/analytics/CMakeFiles/analytics.dir/build
.PHONY : analytics/fast

#=============================================================================
# Target rules for targets named core-app

# Build rule for target.
core-app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core-app
.PHONY : core-app

# fast build rule for target.
core-app/fast:
	$(MAKE) $(MAKESILENT) -f src/core/app/CMakeFiles/core-app.dir/build.make src/core/app/CMakeFiles/core-app.dir/build
.PHONY : core-app/fast

#=============================================================================
# Target rules for targets named core-service

# Build rule for target.
core-service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core-service
.PHONY : core-service

# fast build rule for target.
core-service/fast:
	$(MAKE) $(MAKESILENT) -f src/core/service/CMakeFiles/core-service.dir/build.make src/core/service/CMakeFiles/core-service.dir/build
.PHONY : core-service/fast

#=============================================================================
# Target rules for targets named core-user

# Build rule for target.
core-user: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core-user
.PHONY : core-user

# fast build rule for target.
core-user/fast:
	$(MAKE) $(MAKESILENT) -f src/core/user/CMakeFiles/core-user.dir/build.make src/core/user/CMakeFiles/core-user.dir/build
.PHONY : core-user/fast

#=============================================================================
# Target rules for targets named hf3fs-admin

# Build rule for target.
hf3fs-admin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hf3fs-admin
.PHONY : hf3fs-admin

# fast build rule for target.
hf3fs-admin/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/CMakeFiles/hf3fs-admin.dir/build.make src/tools/CMakeFiles/hf3fs-admin.dir/build
.PHONY : hf3fs-admin/fast

#=============================================================================
# Target rules for targets named admin-commands

# Build rule for target.
admin-commands: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 admin-commands
.PHONY : admin-commands

# fast build rule for target.
admin-commands/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/commands/CMakeFiles/admin-commands.dir/build.make src/tools/commands/CMakeFiles/admin-commands.dir/build
.PHONY : admin-commands/fast

#=============================================================================
# Target rules for targets named hf3fs_fuse

# Build rule for target.
hf3fs_fuse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hf3fs_fuse
.PHONY : hf3fs_fuse

# fast build rule for target.
hf3fs_fuse/fast:
	$(MAKE) $(MAKESILENT) -f src/fuse/CMakeFiles/hf3fs_fuse.dir/build.make src/fuse/CMakeFiles/hf3fs_fuse.dir/build
.PHONY : hf3fs_fuse/fast

#=============================================================================
# Target rules for targets named hf3fs_fuse_main

# Build rule for target.
hf3fs_fuse_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hf3fs_fuse_main
.PHONY : hf3fs_fuse_main

# fast build rule for target.
hf3fs_fuse_main/fast:
	$(MAKE) $(MAKESILENT) -f src/fuse/CMakeFiles/hf3fs_fuse_main.dir/build.make src/fuse/CMakeFiles/hf3fs_fuse_main.dir/build
.PHONY : hf3fs_fuse_main/fast

#=============================================================================
# Target rules for targets named simple_example

# Build rule for target.
simple_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_example
.PHONY : simple_example

# fast build rule for target.
simple_example/fast:
	$(MAKE) $(MAKESILENT) -f src/simple_example/CMakeFiles/simple_example.dir/build.make src/simple_example/CMakeFiles/simple_example.dir/build
.PHONY : simple_example/fast

#=============================================================================
# Target rules for targets named simple_example_main

# Build rule for target.
simple_example_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_example_main
.PHONY : simple_example_main

# fast build rule for target.
simple_example_main/fast:
	$(MAKE) $(MAKESILENT) -f src/simple_example/CMakeFiles/simple_example_main.dir/build.make src/simple_example/CMakeFiles/simple_example_main.dir/build
.PHONY : simple_example_main/fast

#=============================================================================
# Target rules for targets named migration

# Build rule for target.
migration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 migration
.PHONY : migration

# fast build rule for target.
migration/fast:
	$(MAKE) $(MAKESILENT) -f src/migration/CMakeFiles/migration.dir/build.make src/migration/CMakeFiles/migration.dir/build
.PHONY : migration/fast

#=============================================================================
# Target rules for targets named migration_main

# Build rule for target.
migration_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 migration_main
.PHONY : migration_main

# fast build rule for target.
migration_main/fast:
	$(MAKE) $(MAKESILENT) -f src/migration/CMakeFiles/migration_main.dir/build.make src/migration/CMakeFiles/migration_main.dir/build
.PHONY : migration_main/fast

#=============================================================================
# Target rules for targets named test-fabric-lib

# Build rule for target.
test-fabric-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-fabric-lib
.PHONY : test-fabric-lib

# fast build rule for target.
test-fabric-lib/fast:
	$(MAKE) $(MAKESILENT) -f tests/lib/CMakeFiles/test-fabric-lib.dir/build.make tests/lib/CMakeFiles/test-fabric-lib.dir/build
.PHONY : test-fabric-lib/fast

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) $(MAKESILENT) -f tests/main/CMakeFiles/test_main.dir/build.make tests/main/CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

#=============================================================================
# Target rules for targets named test_common

# Build rule for target.
test_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_common
.PHONY : test_common

# fast build rule for target.
test_common/fast:
	$(MAKE) $(MAKESILENT) -f tests/common/CMakeFiles/test_common.dir/build.make tests/common/CMakeFiles/test_common.dir/build
.PHONY : test_common/fast

#=============================================================================
# Target rules for targets named test_analytics

# Build rule for target.
test_analytics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_analytics
.PHONY : test_analytics

# fast build rule for target.
test_analytics/fast:
	$(MAKE) $(MAKESILENT) -f tests/analytics/CMakeFiles/test_analytics.dir/build.make tests/analytics/CMakeFiles/test_analytics.dir/build
.PHONY : test_analytics/fast

#=============================================================================
# Target rules for targets named test_meta

# Build rule for target.
test_meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_meta
.PHONY : test_meta

# fast build rule for target.
test_meta/fast:
	$(MAKE) $(MAKESILENT) -f tests/meta/CMakeFiles/test_meta.dir/build.make tests/meta/CMakeFiles/test_meta.dir/build
.PHONY : test_meta/fast

#=============================================================================
# Target rules for targets named fdb_loopback

# Build rule for target.
fdb_loopback: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fdb_loopback
.PHONY : fdb_loopback

# fast build rule for target.
fdb_loopback/fast:
	$(MAKE) $(MAKESILENT) -f tests/scripts/CMakeFiles/fdb_loopback.dir/build.make tests/scripts/CMakeFiles/fdb_loopback.dir/build
.PHONY : fdb_loopback/fast

#=============================================================================
# Target rules for targets named test_client

# Build rule for target.
test_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_client
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	$(MAKE) $(MAKESILENT) -f tests/client/CMakeFiles/test_client.dir/build.make tests/client/CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

#=============================================================================
# Target rules for targets named test_kv

# Build rule for target.
test_kv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_kv
.PHONY : test_kv

# fast build rule for target.
test_kv/fast:
	$(MAKE) $(MAKESILENT) -f tests/kv/CMakeFiles/test_kv.dir/build.make tests/kv/CMakeFiles/test_kv.dir/build
.PHONY : test_kv/fast

#=============================================================================
# Target rules for targets named test_storage

# Build rule for target.
test_storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage
.PHONY : test_storage

# fast build rule for target.
test_storage/fast:
	$(MAKE) $(MAKESILENT) -f tests/storage/CMakeFiles/test_storage.dir/build.make tests/storage/CMakeFiles/test_storage.dir/build
.PHONY : test_storage/fast

#=============================================================================
# Target rules for targets named test_storage_client

# Build rule for target.
test_storage_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage_client
.PHONY : test_storage_client

# fast build rule for target.
test_storage_client/fast:
	$(MAKE) $(MAKESILENT) -f tests/storage/client/CMakeFiles/test_storage_client.dir/build.make tests/storage/client/CMakeFiles/test_storage_client.dir/build
.PHONY : test_storage_client/fast

#=============================================================================
# Target rules for targets named test_storage_service

# Build rule for target.
test_storage_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage_service
.PHONY : test_storage_service

# fast build rule for target.
test_storage_service/fast:
	$(MAKE) $(MAKESILENT) -f tests/storage/service/CMakeFiles/test_storage_service.dir/build.make tests/storage/service/CMakeFiles/test_storage_service.dir/build
.PHONY : test_storage_service/fast

#=============================================================================
# Target rules for targets named test_storage_store

# Build rule for target.
test_storage_store: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage_store
.PHONY : test_storage_store

# fast build rule for target.
test_storage_store/fast:
	$(MAKE) $(MAKESILENT) -f tests/storage/store/CMakeFiles/test_storage_store.dir/build.make tests/storage/store/CMakeFiles/test_storage_store.dir/build
.PHONY : test_storage_store/fast

#=============================================================================
# Target rules for targets named test_storage_sync

# Build rule for target.
test_storage_sync: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_storage_sync
.PHONY : test_storage_sync

# fast build rule for target.
test_storage_sync/fast:
	$(MAKE) $(MAKESILENT) -f tests/storage/sync/CMakeFiles/test_storage_sync.dir/build.make tests/storage/sync/CMakeFiles/test_storage_sync.dir/build
.PHONY : test_storage_sync/fast

#=============================================================================
# Target rules for targets named mgmtd-test-helper

# Build rule for target.
mgmtd-test-helper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mgmtd-test-helper
.PHONY : mgmtd-test-helper

# fast build rule for target.
mgmtd-test-helper/fast:
	$(MAKE) $(MAKESILENT) -f tests/mgmtd/CMakeFiles/mgmtd-test-helper.dir/build.make tests/mgmtd/CMakeFiles/mgmtd-test-helper.dir/build
.PHONY : mgmtd-test-helper/fast

#=============================================================================
# Target rules for targets named test_mgmtd

# Build rule for target.
test_mgmtd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mgmtd
.PHONY : test_mgmtd

# fast build rule for target.
test_mgmtd/fast:
	$(MAKE) $(MAKESILENT) -f tests/mgmtd/CMakeFiles/test_mgmtd.dir/build.make tests/mgmtd/CMakeFiles/test_mgmtd.dir/build
.PHONY : test_mgmtd/fast

#=============================================================================
# Target rules for targets named test_migration

# Build rule for target.
test_migration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_migration
.PHONY : test_migration

# fast build rule for target.
test_migration/fast:
	$(MAKE) $(MAKESILENT) -f tests/migration/CMakeFiles/test_migration.dir/build.make tests/migration/CMakeFiles/test_migration.dir/build
.PHONY : test_migration/fast

#=============================================================================
# Target rules for targets named storage_bench

# Build rule for target.
storage_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 storage_bench
.PHONY : storage_bench

# fast build rule for target.
storage_bench/fast:
	$(MAKE) $(MAKESILENT) -f benchmarks/storage_bench/CMakeFiles/storage_bench.dir/build.make benchmarks/storage_bench/CMakeFiles/storage_bench.dir/build
.PHONY : storage_bench/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... AlwaysCheckGit"
	@echo "... Hf3fsJemalloc_project"
	@echo "... apache-arrow-cpp"
	@echo "... cargo_build_all"
	@echo "... check-format"
	@echo "... clang-tidy"
	@echo "... clang-tidy-fix"
	@echo "... clean-all"
	@echo "... core_tools"
	@echo "... dump-config"
	@echo "... fdb_loopback"
	@echo "... format"
	@echo "... mimalloc-obj-target"
	@echo "... uninstall"
	@echo "... unzstd"
	@echo "... unzstd.1"
	@echo "... zstd.1"
	@echo "... zstdcat"
	@echo "... zstdcat.1"
	@echo "... zstdgrep.1"
	@echo "... zstdless.1"
	@echo "... zstdmt"
	@echo "... 3fs_liburing"
	@echo "... MonitorCollectorService-fbs"
	@echo "... absl-lib"
	@echo "... admin-cli"
	@echo "... admin-commands"
	@echo "... admin_cli"
	@echo "... analytics"
	@echo "... block_cache_trace_analyzer_tool"
	@echo "... chunk_engine"
	@echo "... cityhash-lib"
	@echo "... clickhouse-cpp-lib"
	@echo "... clickhouse-cpp-lib-static"
	@echo "... client-lib-common"
	@echo "... common"
	@echo "... common-cli"
	@echo "... core-app"
	@echo "... core-client"
	@echo "... core-service"
	@echo "... core-service-fbs"
	@echo "... core-stub"
	@echo "... core-user"
	@echo "... core-user-fbs"
	@echo "... fdb"
	@echo "... fmt"
	@echo "... folly"
	@echo "... folly_base"
	@echo "... folly_exception_counter"
	@echo "... folly_exception_tracer"
	@echo "... folly_exception_tracer_base"
	@echo "... folly_test_util"
	@echo "... follybenchmark"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... hf3fs-admin"
	@echo "... hf3fs_api"
	@echo "... hf3fs_api_shared"
	@echo "... hf3fs_common_shared"
	@echo "... hf3fs_fuse"
	@echo "... hf3fs_fuse_main"
	@echo "... hf3fs_py_usrbio"
	@echo "... kv"
	@echo "... ldb"
	@echo "... leveldb"
	@echo "... leveldb_logger"
	@echo "... leveldbutil"
	@echo "... libzstd_shared"
	@echo "... libzstd_static"
	@echo "... logging_example"
	@echo "... logging_example_lib"
	@echo "... lz4-lib"
	@echo "... memory-common"
	@echo "... meta"
	@echo "... meta-client"
	@echo "... meta-fbs"
	@echo "... meta-stub"
	@echo "... meta_main"
	@echo "... mgmtd"
	@echo "... mgmtd-client"
	@echo "... mgmtd-fbs"
	@echo "... mgmtd-stub"
	@echo "... mgmtd-test-helper"
	@echo "... mgmtd_main"
	@echo "... migration"
	@echo "... migration-fbs"
	@echo "... migration_main"
	@echo "... mimalloc"
	@echo "... mimalloc-obj"
	@echo "... mimalloc-static"
	@echo "... mimalloc-test-api"
	@echo "... mimalloc-test-api-fill"
	@echo "... mimalloc-test-stress"
	@echo "... monitor_collector"
	@echo "... monitor_collector_main"
	@echo "... rocksdb"
	@echo "... rocksdb-shared"
	@echo "... scn"
	@echo "... simple_example"
	@echo "... simple_example-fbs"
	@echo "... simple_example_main"
	@echo "... sst_dump"
	@echo "... storage"
	@echo "... storage-client"
	@echo "... storage-fbs"
	@echo "... storage_bench"
	@echo "... storage_main"
	@echo "... stubs-common"
	@echo "... test-fabric-lib"
	@echo "... test_analytics"
	@echo "... test_client"
	@echo "... test_common"
	@echo "... test_kv"
	@echo "... test_main"
	@echo "... test_meta"
	@echo "... test_mgmtd"
	@echo "... test_migration"
	@echo "... test_storage"
	@echo "... test_storage_client"
	@echo "... test_storage_service"
	@echo "... test_storage_store"
	@echo "... test_storage_sync"
	@echo "... trace_analyzer"
	@echo "... version-info"
	@echo "... zstd"
	@echo "... zstd-frugal"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/jhyunlee/3FS/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

